CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first VARCHAR(300) NOT NULL,
    last VARCHAR(300 NOT NULL,
    email VARCHAR(300) NOT NULL,
    password VARCHAR(300) NOT NULL,
    datecreated DATETIME NOT NULL DEFAULT (GETDATE)
);
